config/routes.rb
Scope::Application.routes.draw do
	
  resources :contacts

  resources :users

  get "home/index"

   root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
#	attr_accessible :firstName, :lastName
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstName, :lastName)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<title>Scope</title>

		<div id="ContactsBin" class="row">
		
		<div id="UsersList" class="col-sm-4">	
			<div class="span4 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Contacts</div>				
				  <!-- List group -->				  

				 <script>
					var selected_contact_id = 1;
					var last_selected_contact_id = 1;

					function select(name) { 
						if(name.id=="contact_"+(selected_contact_id)) { name.className='list-group-item active'};
						var removeOld = document.getElementById("contact_"+(last_selected_contact_id));
						removeOld.className = 'list-group-item';
						last_selected_contact_id = (selected_contact_id);					
					}
				</script>




				  <ul style="max-height:350px; overflow:auto; overflow-x: hidden;" class="list-group">
			<%itemNum = 0%>
			
			<% @contacts.each do |contact| %>
				<li style="border-radius:0px;" id="contact_<%= contact.id%>" onclick="selected_contact_id = <%= contact.id%>; select(this);" class="list-group-item"><%= contact.firstName %> <%= contact.lastName %></li>
			<%itemNum += 1%>
			<% end %>
				  </ul>




<!--Original fake content
				  <ul style="max-height:350px; overflow:auto; overflow-x: hidden;" class="list-group">
				    <li id="contact_1" onclick="selected_contact_id = 1; select(this);" class="list-group-item active">Oliver Garcia</li>
				    <li id="contact_2" onclick="selected_contact_id = 2; select(this);" class="list-group-item">Joshua Stowers</li>
				    <li id="contact_3" onclick="selected_contact_id = 3; select(this);" class="list-group-item">Jeffrey Baker</li>
				    <li id="contact_4" onclick="selected_contact_id = 4; select(this);" class="list-group-item">Lleane Rodriguez</li>
				    <li id="contact_5" onclick="selected_contact_id = 5; select(this);" class="list-group-item">Evan Gray</li>
				    <li id="contact_6" onclick="selected_contact_id = 6; select(this);" class="list-group-item">Batman</li>
				    <li id="contact_7" onclick="selected_contact_id = 7; select(this);" class="list-group-item">Will Smith</li>
				    <li id="contact_8" onclick="selected_contact_id = 8; select(this);" class="list-group-item">Joe Biden</li>
				    <li id="contact_9" onclick="selected_contact_id = 9; select(this);" class="list-group-item">Aretha Franklin</li>
				    <li id="contact_10" onclick="selected_contact_id = 10; select(this);" class="list-group-item">Cho Chang</li>
				    <li id="contact_11" onclick="selected_contact_id = 11; select(this);" class="list-group-item">Spiderman</li>
				    <li id="contact_12" onclick="selected_contact_id = 12; select(this);" class="list-group-item">Christopher Robin</li>
				    <li id="contact_13" onclick="selected_contact_id = 13; select(this);" class="list-group-item">Nagisa Isa</li>
				    <li id="contact_14" onclick="selected_contact_id = 14; select(this);" class="list-group-item">William Tell</li>
				    <li id="contact_14" onclick="this.className='list-group-item active'; select();" class="list-group-item">William Tell</li>
				  </ul>
-->				  
				  
				  

				
				<div class="panel-footer">
					<!--<button type="button" class="btn btn-danger">Delete</button>-->
					<button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#addContactModal">New</button>
				</div>

			</div>			
		</div>





		<div id="UsersInfo" class="col-sm-8">	
			<div class="span4 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Info</div>

					
					  <!-- List group -->
					  <ul style="max-height:350px; overflow:auto; overflow-x: hidden;" class="list-group">
					  
				  		<div class="panel-body">
				  			<div class="row">
				  				<div class="col-xs-8">
					  				<h3>Contact Name</h3>
					  				<p>Notes: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.</p>
				  				</div>
					  			<div class="col-xs-4">
						  			<%=image_tag("tempContactImage.jpg", alt: "Image", width: '100%', class: 'img-rounded img-contact')%>						  		
						  		</div>
						  	</div>	  		
					  	</div>					  
					  
					    <li class="list-group-item"><b>Email: </b>stowers.joshua@live.com</li>
					    <li class="list-group-item"><b>Email: </b>stowers.joshua@Gmail.com</li>				    
					    <li class="list-group-item"><b>Phone: </b>(210) 846 3998</li>
					    <li class="list-group-item"><b>Mobile: </b>(210) 693 0701</li>					    
					    <li class="list-group-item"><b>Address: </b>1830 Palmer View</li>	
					    <li class="list-group-item"><b>Company: </b>SquareSuits</li>
					  </ul>
					  
					  
					<div class="panel-footer">
						<!--<button type="button" class="btn btn-danger">Delete</button>-->
						<button type="button" class="btn btn-danger btn-sm pull-right">Delete</button>						
						<button type="button" class="btn btn-default btn-sm">Edit</button>
					</div>
			
			</div>
			
		</div><!--/#UsersInfo-->

		</div><!--/.row-->



<!---------------------Temp: Comments area------------------->
	<div class="row">	
		<div class="col-sm-12">	
			<div class="span12 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Ideas and Comments</div>				
				  <!-- List group -->				  


				  <ul style="max-height:200px; overflow:auto; overflow-x: hidden;" class="list-group">
					  <li class="list-group-item">Implement groups! That's essential.</li>
					  <li class="list-group-item">Add list items in my HTML with comments and stuff.</li>
					  <li class="list-group-item">Wow, this is pathetic!</li>
					  <li class="list-group-item">Keep at it, Josh, you're so awesome!</li>
					  <li class="list-group-item">FIRST!</li>
				  </ul>			  
			</div>			
		</div>
	</div>	
<!---------------------Temp: Comments area END------------------->


    <!--</div> /.container -->


<!-- New Contact Modal -->
<div class="modal fade" id="addContactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Add a Contact</h4>
      </div>
      <div name="main" id="main" style="max-height:350px; overflow:auto; overflow-x:hidden; " class="modal-body">

			
			<div class="container">
			    <div class="row clearfix">
					<div class="col-md-12 column">	
						
						<input type="text" class="form-control" placeholder="First name">
						<br />
						<input type="text" class="form-control" placeholder="Middle name">
						<br />
						<input type="text" class="form-control" placeholder="Last name">
						<br />
						<textarea placeholder="Notes" class="form-control" id="notes"></textarea>
						<br />
						<table class="table table-bordered table-hover" id="tab_logic">
							<thead>
								<tr>
									<th class="text-center">
										#
									</th>
									<th class="text-center">
										Type
									</th>
									<th class="text-center">
										Value
									</th>
								</tr>
							</thead>
							<tbody>
								<tr id='addr0'>
									<td>
										1
									</td>
									<td>
										<input type="text" name='type0'  placeholder='Type' class="form-control"/>
									</td>
									<td>
										<input type="text" name='value0' placeholder='Value' class="form-control"/>
									</td>
			
								</tr>
			                    <tr id='addr1'></tr>
							</tbody>
						</table>
					</div>
				</div>
				<a onClick="pageScroll()" id="add_row" class="pull-left">Add</a><a id='delete_row' class="pull-right">Delete</a>
			
				<!-----JS for "Add" button - start----------->
				<script>
					function pageScroll() {			
				    	main.scrollBy(0,50); // horizontal and vertical scroll increments
					}
				</script>
				<!------JS for "Add" button - finish--------->
			</div>
			




        
        
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Add</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->








<!---------------------Original page START------------------->
	<div class="row">	
		<div class="col-sm-12">	
			<div class="span12 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Original Page</div>				
				  <!-- List group -->				  

				  <div style="padding:0px 25px 20px 25px;">
						<h1>Listing contacts</h1>
						
						<table>
						  <thead>
						    <tr>
						      <th>Firstname</th>
						      <th>Lastname</th>
						      <th></th>
						      <th></th>
						      <th></th>
						    </tr>
						  </thead>
						
						  <tbody>
						    <% @contacts.each do |contact| %>
						      <tr>
						        <td><%= contact.firstName %></td>
						        <td><%= contact.lastName %></td>
						        <td style="padding:3px;"><%= link_to 'Show', contact %></td>
						        <td style="padding:3px;"><%= link_to 'Edit', edit_contact_path(contact) %></td>
						        <td style="padding:3px;"><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						      </tr>
						    <% end %>
						  </tbody>
						</table>
						
						<br>
						
						<%= link_to 'New Contact', new_contact_path %>

				  </div>
			</div>			
		</div>
	</div>	
<!---------------------Original page END------------------->

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @contact.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact.lastName %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<title>Scope</title>

		<div id="ContactsBin" class="row">
		
		<div id="UsersList" class="col-sm-4">	
			<div class="span4 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Contacts</div>				
				  <!-- List group -->				  

				 <script>
					var selected_contact_id = 1;
					var last_selected_contact_id = 1;

					function select(name) { 
						if(name.id=="contact_"+(selected_contact_id)) { name.className='list-group-item active'};
						var removeOld = document.getElementById("contact_"+(last_selected_contact_id));
						removeOld.className = 'list-group-item';
						last_selected_contact_id = (selected_contact_id);					
					}
				</script>




				  <ul style="height:60vh; overflow:auto; overflow-x: hidden;" class="list-group">
			<%itemNum = 0%>
			
			<% @contacts.each do |contact| %>
				<li style="border-radius:0px;" id="contact_<%= contact.id%>" onclick="selected_contact_id = <%= contact.id%>; select(this);" class="list-group-item"><%= contact.firstName %> <%= contact.lastName %></li>
			<%itemNum += 1%>
			<% end %>
				  </ul>




<!--Original fake content
				  <ul style="max-height:350px; overflow:auto; overflow-x: hidden;" class="list-group">
				    <li id="contact_1" onclick="selected_contact_id = 1; select(this);" class="list-group-item active">Oliver Garcia</li>
				    <li id="contact_2" onclick="selected_contact_id = 2; select(this);" class="list-group-item">Joshua Stowers</li>
				    <li id="contact_3" onclick="selected_contact_id = 3; select(this);" class="list-group-item">Jeffrey Baker</li>
				    <li id="contact_4" onclick="selected_contact_id = 4; select(this);" class="list-group-item">Lleane Rodriguez</li>
				    <li id="contact_5" onclick="selected_contact_id = 5; select(this);" class="list-group-item">Evan Gray</li>
				    <li id="contact_6" onclick="selected_contact_id = 6; select(this);" class="list-group-item">Batman</li>
				    <li id="contact_7" onclick="selected_contact_id = 7; select(this);" class="list-group-item">Will Smith</li>
				    <li id="contact_8" onclick="selected_contact_id = 8; select(this);" class="list-group-item">Joe Biden</li>
				    <li id="contact_9" onclick="selected_contact_id = 9; select(this);" class="list-group-item">Aretha Franklin</li>
				    <li id="contact_10" onclick="selected_contact_id = 10; select(this);" class="list-group-item">Cho Chang</li>
				    <li id="contact_11" onclick="selected_contact_id = 11; select(this);" class="list-group-item">Spiderman</li>
				    <li id="contact_12" onclick="selected_contact_id = 12; select(this);" class="list-group-item">Christopher Robin</li>
				    <li id="contact_13" onclick="selected_contact_id = 13; select(this);" class="list-group-item">Nagisa Isa</li>
				    <li id="contact_14" onclick="selected_contact_id = 14; select(this);" class="list-group-item">William Tell</li>
				    <li id="contact_14" onclick="this.className='list-group-item active'; select();" class="list-group-item">William Tell</li>
				  </ul>
-->				  
				  
				  

				
				<div class="panel-footer">
					<!--<button type="button" class="btn btn-danger">Delete</button>-->
					<button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#addContactModal">New</button>
				</div>

			</div>			
		</div>





		<div id="UsersInfo" class="col-sm-8">	
			<div class="span4 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Info</div>

					
					  <!-- List group -->
					  <ul style="height:60vh; overflow:auto; overflow-x: hidden;" class="list-group">
					  
				  		<div class="panel-body">
				  			<div class="row">
				  				<div class="col-xs-8">
					  				<h3>Contact Name</h3>
					  				<p>Notes: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.</p>
				  				</div>
					  			<div class="col-xs-4">
						  			<%=image_tag("tempContactImage.jpg", alt: "Image", width: '100%', class: 'img-rounded img-contact')%>						  		
						  		</div>
						  	</div>	  		
					  	</div>					  
					  
					    <li class="list-group-item"><b>Email: </b>stowers.joshua@live.com</li>
					    <li class="list-group-item"><b>Email: </b>stowers.joshua@Gmail.com</li>				    
					    <li class="list-group-item"><b>Phone: </b>(210) 846 3998</li>
					    <li class="list-group-item"><b>Mobile: </b>(210) 693 0701</li>					    
					    <li class="list-group-item"><b>Address: </b>1830 Palmer View</li>	
					    <li class="list-group-item"><b>Company: </b>SquareSuits</li>
					  </ul>
					  
					  
					<div class="panel-footer">
						<!--<button type="button" class="btn btn-danger">Delete</button>-->
						<button type="button" class="btn btn-danger btn-sm pull-right">Delete</button>						
						<button type="button" class="btn btn-default btn-sm">Edit</button>
					</div>
			
			</div>
			
		</div><!--/#UsersInfo-->

		</div><!--/.row-->



<!---------------------Temp: Comments area------------------->
	<div class="row">	
		<div class="col-sm-12">	
			<div class="span12 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Ideas and Comments</div>				
				  <!-- List group -->				  


				  <ul style="max-height:200px; overflow:auto; overflow-x: hidden;" class="list-group">
					  <li class="list-group-item">Implement groups! That's essential.</li>
					  <li class="list-group-item">Add list items in my HTML with comments and stuff.</li>
					  <li class="list-group-item">Wow, this is pathetic!</li>
					  <li class="list-group-item">Keep at it, Josh, you're so awesome!</li>
					  <li class="list-group-item">FIRST!</li>
				  </ul>			  
			</div>			
		</div>
	</div>	
<!---------------------Temp: Comments area END------------------->


    <!--</div> /.container -->


<!-- New Contact Modal -->
<div class="modal fade" id="addContactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Add a Contact</h4>
      </div>
      <div name="main" id="main" style="max-height:350px; overflow:auto; overflow-x:hidden; " class="modal-body">

			
			<div class="container">
			    <div class="row clearfix">
					<div class="col-md-12 column">	
						
						<input type="text" class="form-control" placeholder="First name">
						<br />
						<input type="text" class="form-control" placeholder="Middle name">
						<br />
						<input type="text" class="form-control" placeholder="Last name">
						<br />
						<textarea placeholder="Notes" class="form-control" id="notes"></textarea>
						<br />
						<table class="table table-bordered table-hover" id="tab_logic">
							<thead>
								<tr>
									<th class="text-center">
										#
									</th>
									<th class="text-center">
										Type
									</th>
									<th class="text-center">
										Value
									</th>
								</tr>
							</thead>
							<tbody>
								<tr id='addr0'>
									<td>
										1
									</td>
									<td>
										<input type="text" name='type0'  placeholder='Type' class="form-control"/>
									</td>
									<td>
										<input type="text" name='value0' placeholder='Value' class="form-control"/>
									</td>
			
								</tr>
			                    <tr id='addr1'></tr>
							</tbody>
						</table>
					</div>
				</div>
				<a onClick="pageScroll()" id="add_row" class="pull-left">Add</a><a id='delete_row' class="pull-right">Delete</a>
			
				<!-----JS for "Add" button - start----------->
				<script>
					function pageScroll() {			
				    	main.scrollBy(0,50); // horizontal and vertical scroll increments
					}
				</script>
				<!------JS for "Add" button - finish--------->
			</div>
			




        
        
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Add</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->








<!---------------------Original page START------------------->
	<div class="row">	
		<div class="col-sm-12">	
			<div class="span12 panel panel-default">
				  <!-- Default panel contents -->
				  <div class="panel-heading">Original Page</div>				
				  <!-- List group -->				  

				  <div style="padding:0px 25px 20px 25px;">
						<h1>Listing contacts</h1>
						
						<table>
						  <thead>
						    <tr>
						      <th>Firstname</th>
						      <th>Lastname</th>
						      <th></th>
						      <th></th>
						      <th></th>
						    </tr>
						  </thead>
						
						  <tbody>
						    <% @contacts.each do |contact| %>
						      <tr>
						        <td><%= contact.firstName %></td>
						        <td><%= contact.lastName %></td>
						        <td style="padding:3px;"><%= link_to 'Show', contact %></td>
						        <td style="padding:3px;"><%= link_to 'Edit', edit_contact_path(contact) %></td>
						        <td style="padding:3px;"><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						      </tr>
						    <% end %>
						  </tbody>
						</table>
						
						<br>
						
						<%= link_to 'New Contact', new_contact_path %>

				  </div>
			</div>			
		</div>
	</div>	
<!---------------------Original page END------------------->

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>